# Spring Application Name
spring.application.name=backend

# Supabase PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.oxkwycjmnrcowylhajnh
spring.datasource.password=RubraDB30072026

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Google API Credentials for OAuth Flow
google.client.id=${GOOGLE_CLIENT_ID:example-client-id}
google.client.secret=${GOOGLE_CLIENT_SECRET:example-client-secret}
